a = ["a",'b','c','d']#work as i...
b = [1,2,3,4,]#work as j...
for i, j in zip(a,b):# this line starts the loop and merge both values of a &b..
    print("%s is %s " % (i,j))#prints the valuses of a&b as formatted string...
    