def sentence_builder(phrase): # *define a fucn with arg 'phrase'....
    capital_sent = phrase.capitalize() # !create a variable which will capitalize the sentence as provied inside the func
    if phrase.startswith(('how','what', 'why','who')): # TODO: to check weather sentence starts with an interogative word...
        return f'{capital_sent}? '# ! if above statemnet is true, then sentence will end up with a ?...
    else:
        return f'{capital_sent}.'

result = [] # !Here we consider a list beacuse our desire output includes more than one item....
while True:
    user_input = input('say something :')
    if user_input == '/end':
        break
    else:
        result.append(sentence_builder(user_input))
    #* above line will provide the final output as it append the each item of the pharse in the empty
    #* empty list "result"......
         
print(' '.join(result)) #! here join method will join multiple items in a list and remove [] for you...
